folders_path: '//RU-MOWRAS005/Projects/_Project folders/2022 - Rostselmash - Budgeting control MTS/Client`s info'
filename_max_length: 60  # default 60 symbols


#excel_file_part
excel_file_path: '//RU-MOWRAS005/Projects/_Project folders/2022 - Rostselmash - Budgeting control MTS/Client`s info/РСМ_Budgeting control MTS_Инфозапрос_v6.2.xlsx'
skiprows: 6
usecols:
  - 2
  - 3
words_to_del:
  - по
  - в
  - и
  - на
  - с
  - для
  - от

names_pattern_from_file: r"(\d+)"